
image: node:alpine

variables:
  PUBLIC_URL: /portfolio

cache:
  paths:
  - node_modules


stages:
- deploy

pages:
  stage: deploy
  script:
    - npm install # Install all dependencies
    - npm run build # Build for prod
    - mv dist public # CRA and gitlab pages both use the public folder. Only do this in a build pipeline.
  artifacts:
    paths:
    - public # The built files for Gitlab Pages to serve
  only:
    - master # Only run on master branch